### PR TITLE
feat: add windows / jdk8 images for LTSC 2019

### PR DESCRIPTION
**Pull request by garethjevans**

### CODE REVIEW

**Comment by slide** [comment]
Is there a need to have jdk8 versions of these?

**Comment by garethjevans** [comment]
@slide, when speaking to @MarkEWaite yesterday, he felt that providing agent builds for jdk8 would be required.

**Comment by slide** [comment]
I'm not sure why that is the case, maybe we can have a discussion about it.

**Comment by MarkEWaite** [comment]
@slide CloudBees has customers that want to use JDK 8 Windows agent images as part of their use of the CloudBees product.  We discussed it internally at CloudBees and tried to strike the best balance between open source in the Jenkins project and the proprietary infrastructure that CloudBees uses to support their customers.  We thought that adding the JDK 8 Windows agent in the Jenkins project would benefit Jenkins users and also be usable for CloudBees customers.  Gareth and I will continue to monitor and maintain the JDK 8 Windows agent image so that we are confident it will work for CloudBees customers.

We're also fine switching and doing that work inside the CloudBees infrastructure if you would rather not have it done in the Jenkins project.

**Comment by slide** [comment]
If there are people who want it, it's fine, I just wanted to make sure there was an actual need and not just adding it for a "complete" set of images.

**Pull request merged**
