### PR TITLE
fix(windows): correct `git-lfs` installation and bump of its version to 3.4.1

### PR DESCRIPTION
**Pull request by lemeurherve**
Same as https://github.com/jenkinsci/docker-agent/pull/503, this PR mainly add `git` to the `PATH` ~**before** running `git-lfs.exe install` instead of `git lfs install`~ and unzip git-lfs archive to the correct location to avoir the error `git: 'lfs' is not a git command.` encountered when bumping `git-lfs` to its `3.4.1` version, cf https://github.com/jenkinsci/docker-ssh-agent/pull/277#issuecomment-1630239571

Other notable changes:
- test added to check if git-lfs (and thus git) is installed and in the PATH
- trimprefix added to the git-lfs source in the corresponding updatecli manifest, easier to work with in files operations and in test

### Testing done

```[tasklist]
### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

### CODE REVIEW

**Comment by lemeurherve** [comment]
Will probably need #292 & #302

**Comment by lemeurherve** [comment]
> Are these changes are needed in the proposed upgrade to 3.5.1 as well?
> 
> * [Bump `git-lfs` version on Windows to v3.5.1 #366](https://github.com/jenkinsci/docker-ssh-agent/pull/366)

I think so, I need to check that.

**Comment by lemeurherve** [comment]
updatecli is failing as one of its targets isn't in the primary branch yet.

**Comment by lemeurherve** [comment]
From https://ci.jenkins.io/job/Packaging/job/docker-ssh-agent/job/PR-318/21/console

> 00:05:07.923  Git LFS initialized.

🥳 

Tests are still failing, but that's another issue (#292)

**Review by dduportal — APPROVED** [review]

**Pull request merged**
