### PR TITLE
chore(updatecli): Now tracks the JDK versions.

### PR DESCRIPTION
**Pull request by gounthar**
There is already a `JAVA_VERSION` present in the Dockerfiles and the Docker bake file, but it is currently not being handled by `updatecli`.

I would like to propose making the necessary changes to update the Linux and Windows Dockerfiles and the Docker bake file accordingly. 

These modifications are mostly based on the work already done on [`docker-agent`](https://raw.githubusercontent.com/jenkinsci/docker-agent/c9f7b17801eadd0c73437f82af9302ef3cb77738/updatecli/updatecli.d/jdk17.yaml).

### Testing done

```bash
updatecli diff --config updatecli/updatecli.d/temurin.yaml --values updatecl
i/values.github-action.yaml


+++++++++++
+ PREPARE +
+++++++++++

Loading Pipeline "updatecli/updatecli.d/temurin.yaml"

SCM repository retrieved: 1


++++++++++++++++++
+ AUTO DISCOVERY +
++++++++++++++++++



++++++++++++
+ PIPELINE +
++++++++++++



################################
# BUMP TEMURIN'S JDK17 VERSION #
################################


SOURCES
=======

jdk11LastVersion
----------------
Searching for version matching pattern "^jdk-11.(\\d*).(\\d*).(\\d*)(.(\\d*))+(\\d*)$"
✔ Github Release version "jdk-11.0.19+7" found matching pattern "^jdk-11.(\\d*).(\\d*).(\\d*)(.(\\d*))+(\\d*)$"


CHANGELOG:
----------

Release published on the 2023-04-19 15:13:47 +0000 UTC at the url https://github.com/adoptium/temurin11-binaries/releases/tag/jdk-11.0.19%2B7

Official Release of jdk-11.0.19+7

jdk17LastVersion
----------------
Searching for version matching pattern "^jdk-17.(\\d*).(\\d*).(\\d*)(.(\\d*))+(\\d*)$"
✔ Github Release version "jdk-17.0.7+7" found matching pattern "^jdk-17.(\\d*).(\\d*).(\\d*)(.(\\d*))+(\\d*)$"


CHANGELOG:
----------

Release published on the 2023-04-19 13:34:51 +0000 UTC at the url https://github.com/adoptium/temurin17-binaries/releases/tag/jdk-17.0.7%2B7

Official Release of jdk-17.0.7+7


CONDITIONS:
===========

checkTemurinJDK11WindowsCoreDockerImage
---------------------------------------
✔ The Docker image index.docker.io/library/eclipse-temurin:11.0.19_7-jdk-windowsservercore-1809 (amd64) exists and is available.

checkTemurinJDK11DebianDockerImages
-----------------------------------
✔ The Docker image index.docker.io/library/eclipse-temurin:11.0.19_7-jdk-focal (amd64) exists and is available.
✔ The Docker image index.docker.io/library/eclipse-temurin:11.0.19_7-jdk-focal (arm64) exists and is available.
✔ The Docker image index.docker.io/library/eclipse-temurin:11.0.19_7-jdk-focal (s390x) exists and is available.
✔ The Docker image index.docker.io/library/eclipse-temurin:11.0.19_7-jdk-focal (arm/v7) exists and is available.

checkTemurinJDK11AlpineDockerImage
----------------------------------
✔ The Docker image index.docker.io/library/eclipse-temurin:11.0.19_7-jdk-alpine (amd64) exists and is available.

checkTemurinJDK17WindowsCoreDockerImage
---------------------------------------
✔ The Docker image index.docker.io/library/eclipse-temurin:17.0.7_7-jdk-windowsservercore-1809 (amd64) exists and is available.

checkTemurinJDK17DebianDockerImages
-----------------------------------
✔ The Docker image index.docker.io/library/eclipse-temurin:17.0.7_7-jdk-focal (amd64) exists and is available.
✔ The Docker image index.docker.io/library/eclipse-temurin:17.0.7_7-jdk-focal (arm64) exists and is available.
✔ The Docker image index.docker.io/library/eclipse-temurin:17.0.7_7-jdk-focal (s390x) exists and is available.
✔ The Docker image index.docker.io/library/eclipse-temurin:17.0.7_7-jdk-focal (arm/v7) exists and is available.

checkTemurinJDK17AlpineDockerImage
----------------------------------
✔ The Docker image index.docker.io/library/eclipse-temurin:17.0.7_7-jdk-alpine (amd64) exists and is available.


TARGETS
========

setJDK11VersionDockerBake
-------------------------

**Dry Run enabled**

✔ Content from file "/tmp/updatecli/github/jenkinsci/docker-ssh-agent/docker-bake.hcl" already up to date
✔ All contents from 'file' and 'files' combined already up to date

setJDK17VersionDebian
---------------------

**Dry Run enabled**


🐋 On (Docker)file "/tmp/updatecli/github/jenkinsci/docker-ssh-agent/debian/Dockerfile":

✔ The line #1, matched by the keyword "ARG" and the matcher "JAVA_VERSION", is correctly set to "ARG JAVA_VERSION=17.0.7_7".

setJDK17VersionAlpine
---------------------

**Dry Run enabled**


🐋 On (Docker)file "/tmp/updatecli/github/jenkinsci/docker-ssh-agent/alpine/Dockerfile":

⚠ The line #23, matched by the keyword "ARG" and the matcher "JAVA_VERSION", is changed from "ARG JAVA_VERSION=\"17.0.7_7\"" to "ARG JAVA_VERSION=17.0.7_7".

setJDK17VersionDockerBake
-------------------------

**Dry Run enabled**

✔ Content from file "/tmp/updatecli/github/jenkinsci/docker-ssh-agent/docker-bake.hcl" already up to date
✔ All contents from 'file' and 'files' combined already up to date


ACTIONS
========

[Dry Run] An action of kind "github/pullrequest" is expected.

=============================

REPORTS:


⚠ Bump Temurin's JDK17 version:
        Source:
                ✔ [jdk11LastVersion] Get the latest Temurin JDK11 version (kind: githubrelease)
                ✔ [jdk17LastVersion] Get the latest Temurin JDK17 version (kind: githubrelease)
        Condition:
                ✔ [checkTemurinJDK11AlpineDockerImage] Check if the container image "eclipse-temurin:<jdk11LastVersion>-jdk-alpine" is available (kind: dockerimage)
                ✔ [checkTemurinJDK11DebianDockerImages] Check if the container image "eclipse-temurin:<jdk11LastVersion>-jdk-focal" is available (kind: dockerimage)
                ✔ [checkTemurinJDK11WindowsCoreDockerImage] Check if the container image "eclipse-temurin:<jdk11LastVersion>-jdk-windowsservercore-1809" is available (kind: dockerimage)
                ✔ [checkTemurinJDK17AlpineDockerImage] Check if the container image "eclipse-temurin:<jdk17LastVersion>-jdk-alpine" is available (kind: dockerimage)
                ✔ [checkTemurinJDK17DebianDockerImages] Check if the container image "eclipse-temurin:<jdk17LastVersion>-jdk-focal" is available (kind: dockerimage)
                ✔ [checkTemurinJDK17WindowsCoreDockerImage] Check if the container image "eclipse-temurin:<jdk17LastVersion>-jdk-windowsservercore-1809" is available (kind: dockerimage)
        Target:
                ✔ [setJDK11VersionDockerBake] Bump JDK11 version for Linux images in the docker-bake.hcl file (kind: file)
                ⚠ [setJDK17VersionAlpine] Bump JDK17 default ARG version on Alpine Dockerfile (kind: dockerfile)
                ✔ [setJDK17VersionDebian] Bump JDK17 default ARG version on Debian Dockerfile (kind: dockerfile)
                ✔ [setJDK17VersionDockerBake] Bump JDK17 version for Linux images in the docker-bake.hcl file (kind: file)


Run Summary
===========
Pipeline(s) run:
  * Changed:    1
  * Failed:     0
  * Skipped:    0
  * Succeeded:  0
  * Total:      1
```

### Submitter checklist
- [X] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [X] Ensure that the pull request title represents the desired changelog entry
- [X] Please describe what you did
- ~~Link to relevant issues in GitHub or Jira~~
- ~~Link to relevant pull requests, esp. upstream and downstream changes~~
- [X] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by dduportal** [comment]
> I have also made a temporary change from focal to jammy, but it may not be the best idea as jammy is not an LTS release. I can revert that change if necessary.

Better to do it as a subsequent PR. But as part of this PR, you can totally add a second source to the updatecli manifest which would hold the value of used image from the `FROM eclipse-temurin:<..>` instruction, so the condition could use it (never tried this but should be possible)

> Please note that modifications for Windows are not required since we only use JDK11 for this set of operating systems.

For info, https://github.com/jenkinsci/docker-ssh-agent/issues/211 tracks this

**Comment by dduportal** [comment]
Updated the PR to benefit from #257 : the updatecli process should behave better now

**Comment by gounthar** [comment]
> Updated the PR to benefit from #257 : the updatecli process should behave better now

Checks pass now, thanks.

**Comment by dduportal** [comment]
WDYT about updating the PR title?

- `feature` => `chore` because this change, if merged, does not change the content of the produced artifact (e.g. the Docker image).
- `(dependencies)` => `(updatecli)` because it relates to a component of the source code, and we have a top-level directory `updatecli/`
- ~`JDK17` => `JDK` since https://github.com/jenkinsci/docker-ssh-agent/pull/256/commits/6d7e9e80c4db2f1ffefcfb935dbb6f7a704538f8~ (already done ❤️ )

**Review by dduportal — APPROVED** [review]
LGTM!

Please note that, as per the check's updatecli diff, once merged this PR will open a "chore" PR which will remove quotes in a Dockerfile (but it is fine).

**Comment by gounthar** [comment]
Thanks a lot, Damien.
I've seen that in the automatic PR.
Is it something I could have configured with `updatecli`?

**Pull request merged**
