### PR TITLE
jenkins/ssh-agent:alpine looking for Java in wrong place

### LINKED ISSUE #127: jenkins/ssh-agent:alpine looking for Java in wrong place
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

I'm following the directions here:  https://www.jenkins.io/doc/book/using/using-agents/

The agent is your alpine image.

The controller is running on the HV, which is Centos 7

### Reproduction steps

Exactly as described here:  https://www.jenkins.io/doc/book/using/using-agents/

sudo docker run -d --rm --name=agent1 -p 4444:22 \
-e "JENKINS_AGENT_SSH_PUBKEY=ssh-rsa [key stuff]" \
jenkins/ssh-agent:alpine

### Expected Results

8.  You should now see This node is being launched.. If that’s not the case, you can now press the Relaunch agent button and wait a few seconds. You can now click on the Log button on the left, then you should receive
the message: Agent successfully connected and online on the last log line.

### Actual Results

SSHLauncher{host='172.17.0.2', port=22, credentialsId='jenkins', jvmOptions='', javaPath='', prefixStartSlaveCmd='', suffixStartSlaveCmd='', launchTimeoutSeconds=60, maxNumRetries=10, retryWaitTime=15, sshHostKeyVerificationStrategy=hudson.plugins.sshslaves.verifiers.ManuallyTrustedKeyVerificationStrategy, tcpNoDelay=true, trackCredentials=true}
[05/22/22 11:57:52] [SSH] Opening SSH connection to 172.17.0.2:22.
[05/22/22 11:57:52] [SSH] SSH host key matches key seen previously for this host. Connection will be allowed.
[05/22/22 11:57:52] [SSH] Authentication successful.
[05/22/22 11:57:52] [SSH] The remote user's environment is:
BASH=/bin/bash
BASHOPTS=checkwinsize:cmdhist:complete_fullquote:extquote:force_fignore:globasciiranges:hostcomplete:interactive_comments:progcomp:promptvars:sourcepath
BASH_ALIASES=()
BASH_ARGC=()
BASH_ARGV=()
BASH_CMDS=()
BASH_EXECUTION_STRING=set
BASH_LINENO=()
BASH_SOURCE=()
BASH_VERSINFO=([0]="5" [1]="0" [2]="17" [3]="1" [4]="release" [5]="x86_64-alpine-linux-musl")
BASH_VERSION='5.0.17(1)-release'
DIRSTACK=()
EUID=1000
GROUPS=()
HOME=/home/jenkins
HOSTNAME=081269b60664
HOSTTYPE=x86_64
IFS=$' \t\n'
LOGNAME=jenkins
MACHTYPE=x86_64-alpine-linux-musl
MAIL=/var/mail/jenkins
OPTERR=1
OPTIND=1
OSTYPE=linux-musl
PATH=/bin:/usr/bin:/sbin:/usr/sbin
PPID=39
PS4='+ '
PWD=/home/jenkins
SHELL=/bin/bash
SHELLOPTS=braceexpand:hashall:interactive-comments
SHLVL=1
SSH_CLIENT='172.17.0.1 47632 22'
SSH_CONNECTION='172.17.0.1 47632 172.17.0.2 22'
TERM=dumb
UID=1000
USER=jenkins
_=bash
Checking Java version in the PATH
bash: java: command not found
Java is not in the PATH nor configured with the javaPath setting, Jenkins will try to guess where is Java, this guess will be removed in the future. :Launch agents via SSH
[05/22/22 11:57:52] [SSH] Checking java version of /home/jenkins/jdk/bin/java
Couldn't figure out the Java version of /home/jenkins/jdk/bin/java
bash: /home/jenkins/jdk/bin/java: No such file or directory

[05/22/22 11:57:52] [SSH] Checking java version of java
Couldn't figure out the Java version of java
bash: java: command not found

[05/22/22 11:57:52] [SSH] Checking java version of /usr/bin/java
Couldn't figure out the Java version of /usr/bin/java
bash: /usr/bin/java: No such file or directory

[05/22/22 11:57:52] [SSH] Checking java version of /usr/java/default/bin/java
Couldn't figure out the Java version of /usr/java/default/bin/java
bash: /usr/java/default/bin/java: No such file or directory

[05/22/22 11:57:52] [SSH] Checking java version of /usr/java/latest/bin/java
Couldn't figure out the Java version of /usr/java/latest/bin/java
bash: /usr/java/latest/bin/java: No such file or directory

[05/22/22 11:57:52] [SSH] Checking java version of /usr/local/bin/java
Couldn't figure out the Java version of /usr/local/bin/java
bash: /usr/local/bin/java: No such file or directory

[05/22/22 11:57:52] [SSH] Checking java version of /usr/local/java/bin/java
Couldn't figure out the Java version of /usr/local/java/bin/java
bash: /usr/local/java/bin/java: No such file or directory

java.io.IOException: Java not found on hudson.slaves.SlaveComputer@6caae34b. Install Java 8 or Java 11 on the Agent.
	at hudson.plugins.sshslaves.JavaVersionChecker.resolveJava(JavaVersionChecker.java:83)
	at hudson.plugins.sshslaves.SSHLauncher.lambda$launch$0(SSHLauncher.java:453)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
[05/22/22 11:57:52] Launch failed - cleaning up connection
[05/22/22 11:57:52] [SSH] Connection closed.

### Anything else?

bash-5.0# which java
/opt/java/openjdk/bin/java

### PR DESCRIPTION
**Pull request by gounthar**
fixes #127

ssh doesn't source `/etc/profile`, so we have to add the java executable path to `PATH` within the `/etc/environment` file so that `ssh` sources it.
Thanks to @AdamZWinter for spotting that bug and to @dduportal for pointing that fix out.

- [X] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [X] Ensure that the pull request title represents the desired changelog entry
- [X] Please describe what you did
- [X] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Review by dduportal — COMMENTED** [review]
It seems like that there already is a test to check for this behavior: https://github.com/jenkinsci/docker-ssh-agent/blob/2b1769441972617c2cdff7567be91f305c86bfbd/tests/tests.bats#L106

This test did not catch the issue earlier because it has a special case when using alpine image: it spawns a full bash login session...which reads `/etc/profile` and allows java to be reachable. 

Do you mind removing the alpine case and run the same test as debian as part of this PR ? (ideally, without your fix, the test should fail)

**Comment by gounthar** [comment]
Sure!

**Comment by dduportal** [comment]
@gounthar the tests are now exactly what I was looking for, you did good. Many thanks!

The failing reason is most probably because the fix with the `/etc/environment` is not sufficient, or maybe the test itself is flaky and could be improved.

The road for you is to work on reproducing the test error that you see on the ci check locally. I can reproduce on macOS + Docker Desktop with the command `make test-alpine_jdk8` on this PR's code. That should be the same with a Linux or WSL environment (requires GNU `make`).

The idea would be to check the SSH command and try it by yourself on the running container, from the debug output of bats.

**Comment by dduportal** [comment]
(I realize it is not documented in the contributing guide BUT `source ./tests/keys.bash && ssh-add - <<< "${PRIVATE_SSH_KEY}"` could interest you to load the test containers p^rivate key into your SSH agent)

**Comment by gounthar** [comment]
Thanks a lot for your feedback and patience.
I'll setup a local environment to test.

**Comment by dduportal** [comment]
Oh damn, this is a tricky one. If you want to try it by yourself, please do so.

Otherwise, spoiler ahead:

<details><summary>Click to expand</summary>
- Remove the `export `keyword (scripts are source, not executed so only key=value syntax is valid)
- https://stackoverflow.com/questions/66859494/path-is-different-depending-on-how-you-connect-to-container => SSHD in Alpine Linux does not get the `PATH` from `/etc/environment. With a login session (interactive or with the `--login/-l` flag to shells) then the `/etc/profile` is evaluated during login chain, but with Jenkins (or the actual test) it is not.
</details>

=> I confirm that the change that you made to the test is absolutely valid and catches the user problem from #127 🥳

**Comment by gounthar** [comment]
> The road for you is to work on reproducing the test error that you see on the ci check locally. I can reproduce on macOS + Docker Desktop with the command `make test-alpine_jdk8` on this PR's code. That should be the same with a Linux or WSL environment (requires GNU `make`).

It took me a while to get a working environment. It didn't work for me on Windows with Docker Desktop, so I switched to a Ubuntu free tier (courtesy of Oracle).
I now have the error:

```bash
# -- command failed --
# status : 127
# output : bash: line 1: java: command not found
```

That's a first step. 😊

**Comment by gounthar** [comment]
This

```dockerfile
RUN mkdir -p ${JENKINS_AGENT_HOME}/.ssh/ && echo "PATH=${PATH}" >> ${JENKINS_AGENT_HOME}/.ssh/environment && \
    printf "\nPermitUserEnvironment yes" >> /etc/ssh/sshd_config
``` 

was enough to get the test to work.
Let me try that with `Alpine` for `JDK`  11 & 17 now.

**Comment by gounthar** [comment]
Tests for `Alpine` `JDK` 8, 11 & 17 work.

**Review by timja — APPROVED** [review]

**Review by dduportal — APPROVED** [review]

**Pull request merged**
