### PR TITLE
Improve compatibility with jenkins docker-plugin

### LINKED ISSUE #62: Jenkins docker-plugin passes /usr/sbin/sshd command by default
I have been using these images under the impression that they are made to be used with docker-plugin in jenkins to start these containers as ephemeral agents.  However I've today come to the conclusion that most people must be using them for long-running/manually started agents since there's little talk of this issue.

I had previously been having lots of really strange trouble with my linux agents, especially #46 that I have still yet to figure out why it simply does not work.  Then this week I needed to add some infra for windows build containers and ran into another weird issue such that these containers simply were not working for me out of the box.  

As a baseline I was able to run the windows agent image manually and ssh into it successfully to get to a powershell prompt.  BUT when the windows containers were being started by docker plugin, then they would die within 3-4 seconds.  

By calling 'docker log {container}' soon after a container died I was able to see the following error:
```
PS C:\docker_testing\ssh-key-temp> docker logs wonderful_thompson
&: C:\ProgramData\Jenkins\setup-sshd.ps1:88
Line |
  88 |          & $Cmd
     |            ~~~~
     | The term '/usr/sbin/sshd' is not recognized as the name of a
     | cmdlet, function, script file, or operable program. Check the
     | spelling of the name, or if a path was included, verify that
     | the path is correct and try again.

```
Something in the windows container is trying to run /usr/sbin/sshd?  That's definitly not right!  I scoured the code for references to the string /usr/sbin/sshd, and it doesn't exist in the repo.  I looked at line 88 and see this variable is the command line arguments being passed into setup-sshd.  It would seem jenkins is for some reason passing this command into my windows container.  I looked all over my configuration for this agent and there was nothing unusual that should be causing that.  I made a custom version of the image with extra logging and bypasses this line 88, and the container was able to open.  I kept searching for a cause and eventually found:
[This Docker Plugin doc ](https://wiki.jenkins.io/pages/viewpage.action?pageId=74876479) says:
> By default, the docker plugin will execute /usr/sbin/sshd -D, therefore it is not recommended that you set the ENTRYPOINT unless you plan to pass extra arguments from Jenkins

and
[This Docker Plugin issue](https://github.com/jenkinsci/docker-plugin/issues/105) corroborates this default behavior in the context of complaining about it causing problems for their entry point scripts.  The general reaction again is "don't use entrypoint scripts with docker plugin", which I found odd because that's how docker-ssh-agent works, and understandably since it has to add the ssh public keys at startup.

We need our entrypoint script, and there is no (proper) way to make docker-plugin NOT do this, but there is a hacky way:  The logic seems to be if the command you provide in your agent configuration is empty, it will run the image with "/usr/sbin/sshd -D", otherwise it will use what you provide for the command.  So you can put some kind of no-op in there and it will pass that instead of /usr/sbin/sshd.

Setup-sshd, both windows and linux versions, look at that argument: If it was an ssh key provided, adds the sshkey.  If it was not an ssh key, it tries to execute whatever that argument is, if it's null or empty it moves forward in the script to make the environment variables global and then run sshd at the end.

I have always left the command empty, and apparently this has gone unnoticed on my linux agents because /usr/sbin/sshd exists so it doesn't error, but it DOES mean that sshd starts before (and forever blocks) exporting the environment variables to /etc/environment.  (I'm thinking, has THIS been the cause of #46 for me all long?  I will test this)

In windows the same logic follows, setup-sshd detects that "/usr/sbin/sshd" is not an ssh key so it tries to execute it, which is an error in windows, and the container dies immediately.

I understand the need for the peice of code that is like
```
if(![System.String]::IsNullOrWhiteSpace($Cmd)) {
    if($Cmd -match "^ssh-.*") {
        Write-Key $Cmd
    } else {
        & $Cmd
        exit
    }
}
```
You want to easily take the ssh key as a run argument but also allow the flexibility of running alternate commands.

But I propose it be modified to specifically ignore "/usr/sbin/sshd" when passed as the command, as by default by docker-plugin.  On windows this breaks everything, and on linux causes subtle unwanted behavior, and if someone was running sshd command we know we're going to run it in a few lines anyway.

```
# UNTESTED
if(![System.String]::IsNullOrWhiteSpace($Cmd)) {
    if($Cmd -match "^ssh-.*") {
        Write-Key $Cmd
    } else if($Cmd -match "/usr/sbin/sshd") {
        # ignore default command from jenkins docker plugin
    } else {
        & $Cmd
        exit
    }
}

....
Start-Service sshd
```
Ultimatly I think the true fix for this is in the docker plugin.  Some general solution is needed now that windows containers are a thing.  But doing this would make these images work with docker plugin as a stop gap. The alternative would be some big confusing explanation in the documentation to tell people to put a janky no-op in the command field of their agent configuration.
The same logical fix could be applied to the linux setup-sshd script to make the behavior more predictable (ie not skipping the last part of the script).

If I put one together, would someone be willing to merge a pull request like this, in theory?

### PR DESCRIPTION
**Pull request by GunArm**
Fixes issue #62

### CODE REVIEW

**Comment by GunArm** [comment]
The same tests fail when I run ./make.ps1 test locally on the current master branch.  Are the windows tests currently not working?

**Comment by GunArm** [comment]
Here's the output of the windows container showing the added logging changes, at the top and bottom, with rsa pubkey provided as first param
```
PS C:\docker_testing\ssh-key-temp> docker logs lucid_torvalds
setup-sshd.ps1 param: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDtdWWavvGzQt+GlTV4azrwqlU/PmdaD0VAYTgbkoiCNkYo2M37OZDBF7YM7BQ8Q081rfJiOZjSitzKg0qnDGwzpDCEobVDhPG3zGm+zy5RWDCM8ZXjkZhB/0witP5rQ0MdtI6BoYf99ydqiH8Ex3pp4Vgbds8jZoqW1SkKzb0G+owbDeYUKH4l8hMDayEjhv8ZNhTVY3P/+Rv0Y5p8USNL7NtUGdPM70j3BRQmBfkM8XBofGvbTK3FSzO+AFh1Z72+MwhGm2qCrf+LMh2MnF+sIPT2ZWvHKKRpoqIms9oAAiuQzRRy7a0uj/p4il1fkbat/Mq+IQnwkNdZKktpURoj'
Authorizing ssh pubkey found in params.

Windows IP Configuration


Ethernet adapter vEthernet (Ethernet):

   Connection-specific DNS Suffix  . : lan.mitsi.com
   Link-local IPv6 Address . . . . . : fe80::39f6:ee57:8ee:b354%17
   IPv4 Address. . . . . . . . . . . : 172.28.164.122
   Subnet Mask . . . . . . . . . . . : 255.255.240.0
   Default Gateway . . . . . . . . . : 172.28.160.1

Active Connections

  Proto  Local Address          Foreign Address        State
  TCP    0.0.0.0:22             5ec1fd15d5f9:0         LISTENING
  TCP    0.0.0.0:135            5ec1fd15d5f9:0         LISTENING
  TCP    0.0.0.0:49164          5ec1fd15d5f9:0         LISTENING
  TCP    0.0.0.0:49165          5ec1fd15d5f9:0         LISTENING
  TCP    0.0.0.0:49166          5ec1fd15d5f9:0         LISTENING
  TCP    172.28.161.174:49162   13.88.145.64:https     TIME_WAIT
  TCP    172.28.164.122:49168   13.88.145.64:https     TIME_WAIT
  TCP    [::]:22                5ec1fd15d5f9:0         LISTENING
  TCP    [::]:135               5ec1fd15d5f9:0         LISTENING
  TCP    [::]:49164             5ec1fd15d5f9:0         LISTENING
  TCP    [::]:49165             5ec1fd15d5f9:0         LISTENING
  TCP    [::]:49166             5ec1fd15d5f9:0         LISTENING
  UDP    0.0.0.0:5353           *:*
  UDP    0.0.0.0:5355           *:*
  UDP    [::]:5353              *:*
  UDP    [::]:5355              *:*
5660 2020-09-04 01:05:56.422 Server listening on :: port 22.
5660 2020-09-04 01:05:56.422 Server listening on 0.0.0.0 port 22.
7740 2020-09-04 01:05:57.380 error: kex_exchange_identification: Connection closed by remote host
10768 2020-09-04 01:05:57.380 error: kex_exchange_identification: Connection closed by remote host
9580 2020-09-04 01:05:57.426 WARNING: could not open __PROGRAMDATA__\\ssh/moduli (No such file or directory), using fixed modulus
9580 2020-09-04 01:05:57.595 Received disconnect from 10.6.0.5 port 58116:11: Closed due to user request. [preauth]
9580 2020-09-04 01:05:57.595 Disconnected from 10.6.0.5 port 58116 [preauth]
10284 2020-09-04 01:05:57.724 WARNING: could not open __PROGRAMDATA__\\ssh/moduli (No such file or directory), using fixed modulus
10284 2020-09-04 01:05:57.912 Accepted publickey for jenkins from 10.6.0.5 port 58120 ssh2: RSA SHA256:AZKaUux7uTIWvFrSv6eXNKtW0Wz9y8cHxAKya35dh+g
```

Here it is catching the default docker-plugin `/usr/sbin/sshd -D -p 22` command and ignoring it, rather than halting on error.
```
PS C:\docker_testing\ssh-key-temp> docker logs hardcore_faraday
setup-sshd.ps1 param: '/usr/sbin/sshd'
Ignoring provided (linux) sshd command.

Windows IP Configuration


Ethernet adapter vEthernet (Ethernet):

   Connection-specific DNS Suffix  . : lan.mitsi.com
   Link-local IPv6 Address . . . . . : fe80::5d83:eea5:cb70:c08e%17
   IPv4 Address. . . . . . . . . . . : 172.28.171.136
   Subnet Mask . . . . . . . . . . . : 255.255.240.0
   Default Gateway . . . . . . . . . : 172.28.160.1

Active Connections

  Proto  Local Address          Foreign Address        State
  TCP    0.0.0.0:22             11971dd9823f:0         LISTENING
  TCP    0.0.0.0:135            11971dd9823f:0         LISTENING
  TCP    0.0.0.0:49152          11971dd9823f:0         LISTENING
  TCP    0.0.0.0:49153          11971dd9823f:0         LISTENING
  TCP    0.0.0.0:49154          11971dd9823f:0         LISTENING
  TCP    172.28.171.136:49156   13.88.145.64:https     TIME_WAIT
  TCP    [::]:22                11971dd9823f:0         LISTENING
  TCP    [::]:135               11971dd9823f:0         LISTENING
  TCP    [::]:49152             11971dd9823f:0         LISTENING
  TCP    [::]:49153             11971dd9823f:0         LISTENING
  TCP    [::]:49154             11971dd9823f:0         LISTENING
  UDP    0.0.0.0:5353           *:*
  UDP    0.0.0.0:5355           *:*
  UDP    [::]:5353              *:*
  UDP    [::]:5355              *:*
12248 2020-09-04 01:10:18.520 Server listening on :: port 22.
12248 2020-09-04 01:10:18.520 Server listening on 0.0.0.0 port 22.
9540 2020-09-04 01:10:19.309 error: kex_exchange_identification: Connection closed by remote host
7812 2020-09-04 01:10:19.323 error: kex_exchange_identification: Connection closed by remote host
9384 2020-09-04 01:10:19.363 WARNING: could not open __PROGRAMDATA__\\ssh/moduli (No such file or directory), using fixed modulus
9384 2020-09-04 01:10:19.529 Received disconnect from 10.6.0.5 port 38590:11: Closed due to user request. [preauth]
9384 2020-09-04 01:10:19.529 Disconnected from 10.6.0.5 port 38590 [preauth]
3040 2020-09-04 01:10:19.629 WARNING: could not open __PROGRAMDATA__\\ssh/moduli (No such file or directory), using fixed modulus
3040 2020-09-04 01:10:19.845 Received disconnect from 10.6.0.5 port 38594:11: Closed due to user request. [preauth]
3040 2020-09-04 01:10:19.845 Disconnected from authenticating user jenkins 10.6.0.5 port 38594 [preauth]
```

**Comment by slide** [comment]
I've been meaning to look at the tests but haven't had a chance to do so yet.

**Comment by slide** [comment]
Close and reopen to rebuild after merging in a pester fix

**Comment by slide** [comment]
I think this looks pretty good overall. I will do some testing locally as well.

**Comment by slide** [comment]
Do you think you could add a test around these changes?

**Review by slide — APPROVED** [review]

**Comment by GunArm** [comment]
Last commit fixes linux test which supplied args quoted, while the code (and jenkins-plugin) provide it unquoted.  For consistency I made it support both ways and a test for each, although the second test isn't super useful.

Notably after looking at the code for docker-plugin, there are other forms of this command, the port can be changed, and additional params can get added if using the Inject Credentials setting.  This code only only deals with the literal form of the default command or it would get too complicated and add risk.  I considered removing the linux condition entirely, but kept it because ignoring the param sshd command and running the script sshd command ensures the sshd output goes to the docker logs (with -e flag).

The linux tests pass now, the failure was an intermittent (startup time?) failure on a previously existing test.

**Comment by GunArm** [comment]
I am open to any requests for style fixes or squashing

**Review by oleg-nenashev — APPROVED** [review]
I have tested JDK8 and JDK11 ubuntu images with the patch, they work well. CI is unstable in this repo unfortunately, will try to get it fixed

**Comment by GunArm** [comment]
Is there anything preventing this from being merged?  Conflicts?  Complications?  Needed discussion?

**Comment by GunArm** [comment]
If desired, I could also incorporate the change from PR #68 into my branch so that there is not a merge conflict between them.  The only reason I didn't in the first place is to make this PR less complicated to review.  But since it's been many months, maybe having them in a single branch to merge would make things easier?

**Comment by afischer211** [comment]
Hello, the line 
"elif [[ "$@" == "/usr/sbin/sshd -D -p 22" ]]; then"
in PR#63 does not match in Bash/Linux.

I think, a better solution is using the operator "=~" for regexp-matching:
"elif [[ "$@" =~ /usr/sbin/sshd\ -D\ -p\ 22.* ]]; then"

Here all calls with additional parameters match, but you must mask out the spaces in the (**un-quoted!**) search-pattern.

**Comment by GunArm** [comment]
Hm.  You are saying it doesn't match at all, as in the string is not detected?

My memory is fuzzy because this was back in september, I can do some testing to refresh.  But I was pretty sure I had tested this many ways, including edge casey ways which were not actually likely to occur.
The literal string match _should_ work, but I see you are recommending to improve it by a regex match with a wildcard at the end, implying to me the argument you are receiving has more at the end of it.  I'm curious why/what that is.  Are you testing through docker-plugin or starting containers manually or running the unit tests?  Can you show the actual full argument your setup is producing?

Something which is mentioned above is that there are other arguments docker-plugin can produce if you have something other than the default settings, but trying to support all of those is too much complexity for this stop gap fix.  I'm curious if the reason you have additional characters after the command is because you don't have the default configuration?

**Comment by afischer211** [comment]
Hello, the reason for my investigation is, that the last line of the entrypoint script is not executed. I use the docker-plugin inside jenkins for starting up slave-containers (connected by ssh). Because I want to receive the extended output of ssh with the option -e, I hope on the new version of this script by one of the last pullrequests.
But I must detect, the entrypoint script does not match for the given params of the docker-plugin. They are:
"/usr/sbin/sshd -D -p 22 -o AuthorizedKeysCommand=**** -o AuthorizedKeysCommandUser=****"
So my enhancement with regexp matches and works like expected (shifting out all arguments until the first -o...), the original version does not match and execute the command in the else-branch (without the -e option).

**Pull request merged**
