### PR TITLE
chore(alpine): Tracks alpine linux base version

### LINKED ISSUE #243: Track Alpine Linux base version
Ref. https://github.com/jenkinsci/docker-agent/blob/master/updatecli/updatecli.d/alpine.yaml

### PR DESCRIPTION
**Pull request by gounthar**
Please don't review it yet, as it does not work. 🤷 
I thought I had a `\r\n` problem on my side, but it's worse than that. 😊 

Will close #243 , eventually. 🙄 

I added a new `updatecli` file to track the Alpine versions.
I also modified the `Dockerfile` to add a `ALPINE_TAG` `ARG`.
I modified the `docker-bake.hcl` to add two variables, (`ALPINE_FULL_TAG` and `ALPINE_SHORT_TAG`), and used them later on in the file (as an `ARG` to the Dockerfile, and as an expression in the build of the tags).

### Testing done

```bash
updatecli diff --config updatecli/updatecli.d/alpine.yaml --values updatecli/values.github-action.yaml
```

Unfortunately, it failed... I thought it was a "simple" problem of carriage return/new line, as I mostly copied/pasted from the docker-agent repo, but, alas... It also fails in this PR.

Here is my local trace, just in case there would be something obvious I did not spot:

```bash


+++++++++++
+ PREPARE +
+++++++++++

Loading Pipeline "updatecli/updatecli.d/alpine.yaml"

SCM repository retrieved: 1


++++++++++++++++++
+ AUTO DISCOVERY +
++++++++++++++++++



++++++++++++
+ PIPELINE +
++++++++++++



#######################
# BUMP ALPINE VERSION #
#######################


SOURCES
=======

latestVersion
-------------
WARNING: ⚠ No GitHub Release found, we fallback to published git tags
Searching for version matching pattern "~3"
✔ Github Release version "v3.18.0" found matching pattern "~3"


CHANGELOG:
----------
no GitHub Release found for v3.18.0 on "https://github.com/alpinelinux/aports"


CONDITIONS:
===========

testDockerImageExists
---------------------
✔ The Docker image index.docker.io/library/alpine:3.18.0 (amd64) exists and is available.

testDockerfileArg
-----------------

🐋 On (Docker)file "alpine/Dockerfile":

✔ Line "ARG ALPINE_TAG=3.17.3" found, matching the keyword "ARG" and the matcher "ALPINE_TAG".

testVersionInBakeFile
---------------------
✔ Content of the file "docker-bake.hcl" matched the pattern "(.*ALPINE_FULL_TAG.*)"
✔ Condition on file [] passed


TARGETS
========

updateDockerBake
----------------

**Dry Run enabled**


updateDockerfile
----------------

**Dry Run enabled**


🐋 On (Docker)file "/tmp/updatecli/github/jenkinsci/docker-ssh-agent/alpine/Dockerfile":


ERROR: something went wrong in target "updateDockerBake" : "No line matched in the file \"/tmp/updatecli/github/jenkinsci/docker-ssh-agent/docker-bake.hcl\" for the pattern \"variable(.*)\\\"ALPINE_FULL_TAG\\\"(.*){(.*)(\\\\r\\\\n|\\\\r|\\\\n)(.*)default(.*)=(.*)\""
ERROR: something went wrong in target "updateDockerfile" : "✗ No line found matching the keyword \"ARG\" and the matcher \"ALPINE_TAG\"."

Pipeline "Bump Alpine version" failed
Skipping due to:
        targets stage:  "something went wrong during target execution"

=============================

REPORTS:


✗ Bump Alpine version:
        Source:
                ✔ [latestVersion] Get the latest Alpine Linux version (kind: githubrelease)
        Condition:
                ✔ [testDockerImageExists] Does the Docker Image exist on the Docker Hub? (kind: dockerimage)
                ✔ [testDockerfileArg] Does the Dockerfile have an ARG instruction for the Alpine Linux version? (kind: dockerfile)
                ✔ [testVersionInBakeFile] Does the bake file have variable ALPINE_VERSION (kind: file)
        Target:
                ✗ [updateDockerBake] Update the value of the base image (ARG ALPINE_TAG) in the docker-bake.hcl (kind: file)
                ✗ [updateDockerfile] Update the value of the base image (ARG ALPINE_TAG) in the Dockerfile (kind: dockerfile)


Run Summary
===========
Pipeline(s) run:
  * Changed:    0
  * Failed:     1
  * Skipped:    0
  * Succeeded:  0
  * Total:      1
ERROR: ✗ 1 over 1 pipeline failed
ERROR: command failed
```

### Submitter checklist

- [X] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [X] Ensure that the pull request title represents the desired changelog entry
- [X] Please describe what you did
- [X] Link to relevant issues in GitHub or Jira
- [X] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by dduportal** [comment]
Alas `updatecli` as a really annoying behavior: it runs against the remote principal branch configured in the `values*yaml`file (the branch `master` here). It won't see the changes you made in the current PR.

You can test locally, by commenting out the directive `scmid` from each target of the updatecli manifest file you want to test, but the GitHub CI checks will fail.

However, given the amount of changes in this PR (more than "just" adding an updatecli manifest), I propose to split in 2 PRs:

- A distinct (new) one which goal is to add the new changes (multi-stage in the `Dockerfile` for Alpine, bakefile with the variable, eventually the new tags) to isolate the behavioral changes (and eventual build failures).
- Then we'll update the current PR here to "only" take care of the updatecli tracking


WDYT?

**Comment by gounthar** [comment]
I knew something was wrong with that many changes...
All the lights went red, but I looked elsewhere 😊 

Thanks a lot for the tip about updatecli, I would not have been able to find that easily. 🙏

**Comment by gounthar** [comment]
The latest update from #252 seems to allow this to pass (at least locally, as there seems to be a problem with the Windows part for all of this repo).

```bash
updatecli diff --config updatecli/updatecli.d/alpine.yaml --values updatecli/values.github-action.yaml


+++++++++++
+ PREPARE +
+++++++++++

Loading Pipeline "updatecli/updatecli.d/alpine.yaml"

SCM repository retrieved: 1


++++++++++++++++++
+ AUTO DISCOVERY +
++++++++++++++++++



++++++++++++
+ PIPELINE +
++++++++++++



#######################
# BUMP ALPINE VERSION #
#######################


SOURCES
=======

latestVersion
-------------
WARNING: ⚠ No GitHub Release found, we fallback to published git tags
Searching for version matching pattern "~3"
✔ Github Release version "v3.18.0" found matching pattern "~3"


CHANGELOG:
----------
no GitHub Release found for v3.18.0 on "https://github.com/alpinelinux/aports"


CONDITIONS:
===========

testVersionInBakeFile
---------------------
✔ Content of the file "docker-bake.hcl" matched the pattern "(.*ALPINE_FULL_TAG.*)"
✔ Condition on file [] passed

testDockerImageExists
---------------------
✔ The Docker image index.docker.io/library/alpine:3.18.0 (amd64) exists and is available.

testDockerfileArg
-----------------

🐋 On (Docker)file "alpine/Dockerfile":

✔ Line "ARG ALPINE_TAG=3.17.3" found, matching the keyword "ARG" and the matcher "ALPINE_TAG".


TARGETS
========

updateDockerfile
----------------

**Dry Run enabled**


🐋 On (Docker)file "/tmp/updatecli/github/jenkinsci/docker-ssh-agent/alpine/Dockerfile":

⚠ The line #24, matched by the keyword "ARG" and the matcher "ALPINE_TAG", is changed from "ARG ALPINE_TAG=3.17.3" to "ARG ALPINE_TAG=3.18.0".

updateDockerBake
----------------

**Dry Run enabled**

⚠ updated the [dry run] content of the file "/tmp/updatecli/github/jenkinsci/docker-ssh-agent/docker-bake.hcl"

--- /tmp/updatecli/github/jenkinsci/docker-ssh-agent/docker-bake.hcl
+++ /tmp/updatecli/github/jenkinsci/docker-ssh-agent/docker-bake.hcl
@@ -44,7 +44,7 @@
 }

 variable "ALPINE_FULL_TAG" {
-  default = "3.17.3"
+  default = "3.18.0"
 }

 variable "ALPINE_SHORT_TAG" {



ACTIONS
========

[Dry Run] An action of kind "github/pullrequest" is expected.

=============================

REPORTS:


⚠ Bump Alpine version:
        Source:
                ✔ [latestVersion] Get the latest Alpine Linux version (kind: githubrelease)
        Condition:
                ✔ [testDockerImageExists] Does the Docker Image exist on the Docker Hub? (kind: dockerimage)
                ✔ [testDockerfileArg] Does the Dockerfile have an ARG instruction for the Alpine Linux version? (kind: dockerfile)
                ✔ [testVersionInBakeFile] Does the bake file have variable ALPINE_VERSION (kind: file)
        Target:
                ⚠ [updateDockerBake] Update the value of the base image (ARG ALPINE_TAG) in the docker-bake.hcl (kind: file)
                ⚠ [updateDockerfile] Update the value of the base image (ARG ALPINE_TAG) in the Dockerfile (kind: dockerfile)


Run Summary
===========
Pipeline(s) run:
  * Changed:    1
  * Failed:     0
  * Skipped:    0
  * Succeeded:  0
  * Total:      1
  ```

**Comment by gounthar** [comment]
What I find strange is that the Windows test works on my machine:

```bash
ACTIONS
========

[Dry Run] An action of kind "github/pullrequest" is expected.


###############################
# BUMP GIT VERSION ON WINDOWS #
###############################


SOURCES
=======

lastVersion
-----------
Searching for version matching pattern "v(\\d*)\\.(\\d*)\\.(\\d*)\\.windows\\.(\\d*)$"
✔ Github Release version "v2.41.0.windows.1" found matching pattern "v(\\d*)\\.(\\d*)\\.(\\d*)\\.windows\\.(\\d*)$"


CHANGELOG:
----------

Release published on the 2023-06-01 17:34:43 +0000 UTC at the url https://github.com/git-for-windows/git/releases/tag/v2.41.0.windows.1

Changes since Git for Windows v2.40.1 (April 25th 2023)

As announced previously, Git for Windows will drop support for Windows 7 and for Windows 8 in one of the next versions, following [Cygwin's and MSYS2's lead](https://www.msys2.org/docs/windows_support/) (Git for Windows relies on MSYS2 for components such as Bash and Perl).

Following the footsteps of the MSYS2 and Cygwin projects on which Git for Windows depends, the 32-bit variant of Git for Windows [is being phased out](https://gitforwindows.org/32-bit.html). As of Git for Windows v2.41.0, the 32-bit variant of the POSIX emulation layer (known as "MSYS2 runtime", powering Git Bash among other components shipped with Git for Windows) is in maintenance mode and will only see security bug fixes (if any). Users relying on 32-bit Git for Windows are highly encouraged to switch to the 64-bit version whenever possible.

Please also note that the code-signing certificate used to sign Git for Windows' executables was renewed and may cause Smart Screen to show a warning until the certificate has gained a certain minimum reputation.

### New Features

* Comes with [Git v2.41.0](https://github.com/git/git/blob/v2.41.0/Documentation/RelNotes/2.41.0.txt).
* Comes with [OpenSSH v9.3p1](https://www.openssh.com/txt/release-9.3)
* Comes with [MinTTY v3.6.4](https://github.com/mintty/mintty/releases/tag/3.6.4).
* The Git for Windows installer now [also includes](https://github.com/git-for-windows/build-extra/pull/491) the Git LFS documentation (i.e. `git help git-lfs` now works).
* Comes with [Perl v5.36.1](http://search.cpan.org/dist/perl-5.36.1/pod/perldelta.pod).
* Comes with [GNU Privacy Guard v2.2.41](https://dev.gnupg.org/source/gnupg/browse/STABLE-BRANCH-2-2/NEWS;gnupg-2.2.41?blame=off).
* Comes with [Git Credential Manager v2.1.2](https://github.com/git-ecosystem/git-credential-manager/releases/tag/v2.1.2).
* Comes with MSYS2 runtime (Git for Windows flavor) based on [Cygwin 3.4.6](https://inbox.sourceware.org/cygwin-announce/20230214142733.1052688-1-corinna-cygwin@cygwin.com/). (This does not extend to 32-bit Git for Windows, which [is stuck with v3.3.* of the MSYS2 runtime forever](https://github.com/git-for-windows/git/issues/4279).)
* To help with Git for Windows' release mechanics, Git for Windows now ships [with two variants of `libcurl`](https://github.com/git-for-windows/git/pull/4410).
* Comes with [cURL v8.1.2](https://curl.se/changes.html#8_1_2).
* Comes with [OpenSSL v1.1.1u](https://www.openssl.org/news/openssl-1.1.1-notes.html).

### Bug Fixes

* Git GUI's `Repository>Explore Working Copy` [was broken since v2.39.1](https://github.com/git-for-windows/git/issues/4356), which has been fixed.
* The MSYS2 runtime was adjusted to [prepare for an upcoming Windows version](https://github.com/git-for-windows/git/issues/4429).

Filename | SHA-256
-------- | -------
Git-2.41.0-64-bit.exe | 45dc30410916b8ec5501be39d01d5b60535731c04fa68283b4f9df4920877d4e
Git-2.41.0-32-bit.exe | 25c9077aa60aca41fa8a7b89a8581492e04155786799653ef3010d165e11000e
PortableGit-2.41.0-64-bit.7z.exe | fcbaeffd24fdf435a1f7844825253509136377915e6720aa66aa256ec1f83c30
PortableGit-2.41.0-32-bit.7z.exe | 12190f5bec59a187ec0368f39dba55a7802706076b91fe400ef5da4247999467
MinGit-2.41.0-64-bit.zip | c9cffc25e2ef81f51029138678b7bfc538a56095ec0538125dc790a01e20d77a
MinGit-2.41.0-32-bit.zip | 2643d9b1c663258bc5ec966f2b8493884ba3e247a41edc5a1496068a0a0a6ef4
MinGit-2.41.0-busybox-64-bit.zip | 6ca0a62dea4440a9564b93a85f0dd0b3db27e53782b5ade5a82382d7abc1453c
MinGit-2.41.0-busybox-32-bit.zip | 9e069bffb19da682fb80ef1c3d6c98417dd604cc0e2e1c1c7f23c0edd704aec6
Git-2.41.0-64-bit.tar.bz2 | 4f213f90ff3ef3e9c1bc4184b3cd8e9735f7108be0e4bf846158b9f8c4d5130d
Git-2.41.0-32-bit.tar.bz2 | 9cc7c2a9450b82ec6bb93ba15a192bbab52907ceff018366a189ce66d63b4b06



TARGETS
========

setGitPackagePatchJDK11WindowsNanoserver1809
--------------------------------------------

**Dry Run enabled**


🐋 On (Docker)file "/tmp/updatecli/github/jenkinsci/docker-ssh-agent/windows/nanoserver-ltsc2019/Dockerfile":

✔ The line #43, matched by the keyword "ARG" and the matcher "GIT_PATCH_VERSION", is correctly set to "ARG GIT_PATCH_VERSION=1".

setGitVersionJDK11WindowsNanoserver1809
---------------------------------------

**Dry Run enabled**


🐋 On (Docker)file "/tmp/updatecli/github/jenkinsci/docker-ssh-agent/windows/nanoserver-ltsc2019/Dockerfile":

⚠ The line #42, matched by the keyword "ARG" and the matcher "GIT_VERSION", is changed from "ARG GIT_VERSION=2.40.1" to "ARG GIT_VERSION=2.41.0".

setGitPackagePatchJDK11WindowsServer2019
----------------------------------------

**Dry Run enabled**


🐋 On (Docker)file "/tmp/updatecli/github/jenkinsci/docker-ssh-agent/windows/windowsservercore-ltsc2019/Dockerfile":

✔ The line #41, matched by the keyword "ARG" and the matcher "GIT_PATCH_VERSION", is correctly set to "ARG GIT_PATCH_VERSION=1".

setGitVersionJDK11WindowsServer2019
-----------------------------------

**Dry Run enabled**


🐋 On (Docker)file "/tmp/updatecli/github/jenkinsci/docker-ssh-agent/windows/windowsservercore-ltsc2019/Dockerfile":

⚠ The line #40, matched by the keyword "ARG" and the matcher "GIT_VERSION", is changed from "ARG GIT_VERSION=2.40.1" to "ARG GIT_VERSION=2.41.0".


ACTIONS
========

[Dry Run] An action of kind "github/pullrequest" is expected.

=============================

REPORTS:


⚠ Bump Alpine version:
        Source:
                ✔ [latestVersion] Get the latest Alpine Linux version (kind: githubrelease)
        Condition:
                ✔ [testDockerImageExists] Does the Docker Image exist on the Docker Hub? (kind: dockerimage)
                ✔ [testDockerfileArg] Does the Dockerfile have an ARG instruction for the Alpine Linux version? (kind: dockerfile)
                ✔ [testVersionInBakeFile] Does the bake file have variable ALPINE_VERSION (kind: file)
        Target:
                ⚠ [updateDockerBake] Update the value of the base image (ARG ALPINE_TAG) in the docker-bake.hcl (kind: file)
                ⚠ [updateDockerfile] Update the value of the base image (ARG ALPINE_TAG) in the Dockerfile (kind: dockerfile)


⚠ Bump Git version on Windows:
        Source:
                ✔ [lastVersion] Get the latest Git version (kind: githubrelease)
        Target:
                ✔ [setGitPackagePatchJDK11WindowsNanoserver1809] Update the Git Package Windows patch for JDK11 Windows Nanoserver 1809 (kind: dockerfile)
                ✔ [setGitPackagePatchJDK11WindowsServer2019] Update the Git Package Windows patch for Windows Server Core LTSC2019 (kind: dockerfile)
                ⚠ [setGitVersionJDK11WindowsNanoserver1809] Update the Git Windows version for JDK11 Windows Nanoserver 1809 (kind: dockerfile)
                ⚠ [setGitVersionJDK11WindowsServer2019] Update the Git Windows version for JDK11 Windows Server Core LTSC2019 (kind: dockerfile)


Run Summary
===========
Pipeline(s) run:
  * Changed:    2
  * Failed:     0
  * Skipped:    0
  * Succeeded:  0
  * Total:      2
```

**Review by dduportal — APPROVED** [review]
Nice job 👍🏼 the failure for the check on updatecli is unrelated to the change

**Pull request merged**
