### PR TITLE
feat(JDK21) Use official Temurin build for linux/s390x

### PR DESCRIPTION
**Pull request by gounthar**
This is a follow-up to https://github.com/jenkinsci/docker-agent/pull/772.
@MarkEWaite [noted](https://github.com/jenkinsci/docker-agent/pull/772#issuecomment-2002012356) that we should use the official build versions for the architectures that have moved out of preview.
@dduportal then noted that the only one that was left was s390x.

I'm proposing this small change to remove `s390x`'s JDK from the preview and start using the official Temurin builds.
As `updatecli` now forces us to declare the full architecture for docker images, I also added `linux` and `windows` where needed.

The `updatecli` jdk11 action should fail, as the latest JDK11 Temurin version is only for Mac, and does not exist as a Docker image.

### Testing done

```
updatecli diff --debug --config ./updatecli/updatecli.d/jdk21.yaml --values ./updatecli/values.github-action.yaml
updatecli diff --debug --config ./updatecli/updatecli.d/jdk17.yaml --values ./updatecli/values.github-action.yaml
updatecli diff --debug --config ./updatecli/updatecli.d/jdk11.yaml --values ./updatecli/values.github-action.yaml
```

### Submitter checklist
- [X] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [X] Ensure that the pull request title represents the desired changelog entry
- [X] Please describe what you did
- ~~Link to relevant issues in GitHub or Jira~~
- [X] Link to relevant pull requests, esp. upstream and downstream changes
- [X] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Review by dduportal — CHANGES_REQUESTED** [review]
The build is failing with the following error on the `linux/s390x` step:

```
ERROR: failed to solve: eclipse-temurin:21.0.1_12-jdk-jammy: failed to resolve source metadata for docker.io/library/eclipse-temurin:21.0.1_12-jdk-jammy: no match for platform in manifest: not found
```

The reason is that the JDK21 need to be updated:

- https://hub.docker.com/layers/library/eclipse-temurin/21.0.1_12-jdk-jammy/images/sha256-31d6a3ca757d7aa05451e73d3549338d1f8a838a53851c35241e455eb59a39bf?context=explore does not have a `linux/s390x` image
- While `21.0.2_13` has one: https://hub.docker.com/layers/library/eclipse-temurin/21.0.2_13-jre-jammy/images/sha256-23add05f25ecae9228fa5d2eb3da1028c2710060e4e4350c8d6b15787a186334?context=explore


What do you think about the following plan:

- Update the `updatecli` manifest in a subsequent PR to map to https://github.com/jenkinsci/docker-agent/pull/761
- It will trigger a set of JDK updates (11,17 and 21) through different PRs
- Then we'll be able to rebase the PR here to allow s390x

?

**Comment by gounthar** [comment]
My, oh, my, I'm sorry, I went too fast and just tested the updatecli scripts, and not the image-building part. 😊 
Let me rework that.

**Review by dduportal — APPROVED** [review]
Working since https://github.com/jenkinsci/docker-ssh-agent/pull/383 is applied


👏

**Comment by dduportal** [comment]
Available with the 5.30.0 release: 

- `s390x` is on the `-jdk21` image: https://hub.docker.com/layers/jenkins/ssh-agent/5.30.0-jdk21/images/sha256-e4740f35ab7f9ee34a2f2dbfef7ef55d3ec2075b9ed39b8fd6f184d27e2de178?context=explore
- And no more on the `-jdk21-preview` anymore: https://hub.docker.com/layers/jenkins/ssh-agent/5.30.0-jdk21-preview/images/sha256-f9c99b2644711a6dc1a75bdb8b16c1fb4ecfc8800fc4c49fbe4ac231ac23626b?context=explore

🥳

**Pull request merged**
