### PR TITLE
Switch the JDK 8 Alpine image to AdoptOpenJDK

### PR DESCRIPTION
**Pull request by oleg-nenashev**
Same as https://github.com/jenkinsci/docker/pull/975, bit for the agent. Similar package difference concerns apply, let's discuss them in the controller pull request

- [x] Fix
- [x] Autotests
- [ ] Manual tests?

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
CI for linux images is passing.

The failure is for Windows ones:

```
[2020-08-13T10:37:25.935Z] At C:\Jenkins\workspace\Packaging_docker-ssh-agent_PR-59\tests\sshAgent.Tests.ps1:81 char:9

[2020-08-13T10:37:25.935Z] +         & docker run -d -it --name "$AGENT_CONTAINER" -P "$AGENT_IMAG ...

[2020-08-13T10:37:25.935Z] +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

[2020-08-13T10:37:25.935Z] 

[2020-08-13T10:37:25.935Z]     + CategoryInfo          : NotSpecified: ("docker run" re...ast 1 argument.:String) [], RemoteException

[2020-08-13T10:37:25.935Z] 

[2020-08-13T10:37:25.935Z]     + FullyQualifiedErrorId : NativeCommandError

[2020-08-13T10:37:25.935Z] 

[2020-08-13T10:37:25.935Z]  

[2020-08-13T10:37:25.935Z] 

[2020-08-13T10:37:25.935Z] See 'docker run --help'.

[2020-08-13T10:37:25.935Z] 

[2020-08-13T10:37:25.935Z] Usage:  docker run [OPTIONS] IMAGE [COMMAND] [ARG...]

[2020-08-13T10:37:25.935Z] 

[2020-08-13T10:37:25.935Z] Run a command in a new container

[2020-08-13T10:37:25.935Z] 

[2020-08-13T10:37:54.058Z] [-] Describe [8 windows\windowsservercore-1809] image has setup-sshd.ps1 in the correct location failed

[2020-08-13T10:37:54.058Z]  Expected $true, but got $null.

[2020-08-13T10:37:54.058Z]  at Is-ContainerRunning $AGENT_CONTAINER | Should -BeTrue, C:\Jenkins\workspace\Packaging_docker-ssh-agent_PR-59\tests\sshAgent.Tests.ps1:82

[2020-08-13T10:37:54.058Z]  at <ScriptBlock>, C:\Jenkins\workspace\Packaging_docker-ssh-agent_PR-59\tests\sshAgent.Tests.ps1:82

[2020-08-13T10:37:54.058Z] [-] [8 windows\windowsservercore-1809] checking image metadata.has correct volumes 145ms (143ms|2ms)

[2020-08-13T10:37:54.058Z]  Expected 0, but got 1.

[2020-08-13T10:37:54.058Z]  at $exitCode | Should -Be 0, C:\Jenkins\workspace\Packaging_docker-ssh-agent_PR-59\tests\sshAgent.Tests.ps1:98

[2020-08-13T10:37:54.058Z]  at <ScriptBlock>, C:\Jenkins\workspace\Packaging_docker-ssh-agent_PR-59\tests\sshAgent.Tests.ps1:98

[2020-08-13T10:37:54.058Z] docker : "docker run" requires at least 1 argument.

[2020-08-13T10:37:54.058Z] 

[2020-08-13T10:37:54.058Z] At C:\Jenkins\workspace\Packaging_docker-ssh-agent_PR-59\tests\sshAgent.Tests.ps1:107 char:9

[2020-08-13T10:37:54.058Z] 

[2020-08-13T10:37:54.058Z] +         docker run -d -it --name "$AGENT_CONTAINER" -P "$AGENT_IMAGE" ...

[2020-08-13T10:37:54.058Z] 

[2020-08-13T10:37:54.058Z] +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

[2020-08-13T10:37:54.058Z] 

[2020-08-13T10:37:54.058Z]     + CategoryInfo          : NotSpecified: ("docker run" re...ast 1 argument.:String) [], RemoteException

[2020-08-13T10:37:54.058Z] 

[2020-08-13T10:37:54.058Z]     + FullyQualifiedErrorId : NativeCommandError

[2020-08-13T10:37:54.058Z] 

[2020-08-13T10:37:54.058Z]  

[2020-08-13T10:37:54.058Z] 

[2020-08-13T10:37:54.058Z] See 'docker run --help'.

[2020-08-13T10:37:54.058Z] 

[2020-08-13T10:37:54.058Z] Usage:  docker run [OPTIONS] IMAGE [COMMAND] [ARG...]

[2020-08-13T10:37:54.058Z] 

[2020-08-13T10:37:54.058Z] Run a command in a new contai
```

**Comment by oleg-nenashev** [comment]
Not sure ho, but it looks like `$SHELL` was not passed to https://github.com/oleg-nenashev/docker-ssh-agent/blob/alpine-switch-adoptopenjdk/tests/sshAgent.Tests.ps1#L81 . CC @slide @timja who might have an idea. I do not see such failures in the master branch, but tests there never complete in the builds remaining in the build history

**Comment by slide** [comment]
I'm looking to see if I can reproduce the issue locally

**Comment by oleg-nenashev** [comment]
As agreed in Gitter, I will proceed with a broken Windows flow. This is not a problem if we skip the Windows tags for this release

image

**Pull request merged**
